#!/bin/sh

# check command existence
if [ ! -x /opt/mu-service/wanipcheck/wanip.sh ]; then
    exit 0
fi

/opt/mu-service/wanipcheck/wanip.sh
EXITVALUE=$?
if [ $EXITVALUE != 0 ]; then
    /usr/bin/logger -t mu-service-wanip-wanip "ALERT exited abnormally with [$EXITVALUE]"
fi
exit $EXITVALUE
